name: build-test
on:
  push:
    branches:
      - github-acrions
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Go
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        go-version: [1.13.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    env:
      GO111MODULE: on
    steps:

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }

      - name: Checkout
        uses: actions/checkout@v2

      - name: Go Test
        #        uses: docker://golang:1.13.6
        run: go test -v ./...